spring:
  # Cấu hình kết nối MySQL cho Development
  datasource:
    url: jdbc:mysql://localhost:3306/wcpms?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Cấu hình connection pool
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

  # Cấu hình JPA/Hibernate cho Development
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        connection:
          characterEncoding: UTF-8
          useUnicode: true
        globally_quoted_identifiers: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: congtycophancapnuocphutho@gmail.com
    password: sdri scqr ohzz trsw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Cấu hình Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  sms:
    provider:
      url: "https://api.speedsms.vn/index.php/sms/send" # Ví dụ URL của SpeedSMS
      access-token: "dQ3jGZnhwcevB33Ad0xQxe--sJgNP-7x" # Lấy khi đăng ký tài khoản SMS
      sender-id: "CAPNUOC_PT" # Tên Brandname (nếu có), hoặc để trống
      enabled: true # Cờ để bật/tắt gửi thật (tắt khi dev để đỡ tốn tiền)